name: CI/CD Pipeline

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Run unit tests
      - name: Run unit tests
        run: javac -cp . tests.java && java -cp . org.junit.runner.JUnitCore Tests
        continue-on-error: true

       # Step 3: Code Review
      - name: Code Review
        id: code_review
        run: |
          if [ ${{ job.status }} == 'success' ]; then
   
            # Wait for the senior developer's comment
            echo "Waiting for code review comments..."
            while [[ -z $(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments" | jq -r '.[] | select(.user.login == "landenf") | .body') ]]; do
              sleep 10
            done
            echo "Code review comment received!"
          else
            echo "Unit tests failed. Terminating the workflow."
            exit 1
          fi

      # Step 4: Unlock the branch
      - name: Unlock Branch
        if: steps.code_review.outputs.exit_code == 0
        run: git push origin --delete ${{ github.event.pull_request.head.ref }}
