name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - DEV

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Run unit tests
      - name: Run unit tests
        run: javac -cp . tests.java && java -cp . org.junit.runner.JUnitCore Tests
        continue-on-error: true

      # Step 3: Code Review
      - name: Code Review
        run: |
            if [ ${{ job.status }} == 'success' ]; then
              # Add steps here to request code review and wait for approval
              echo "Unit tests passed. Requesting code review."
              PR_NUMBER=${{ github.event.pull_request.number }}
              curl -s -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -d '{"reviewers": ["sr-dev-username"], "team_reviewers": [], "labels": [], "title": "Code Review Request", "body": "Please review the changes.", "event": "REQUEST_REVIEW", "comments": ""}' "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews"

              # Wait for the senior developer's approval
              echo "Waiting for code review approval..."
              sleep 10
              while [[ $(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews" | jq -r '.[] | select(.user.login == "sr-dev-username" and .state == "APPROVED") | .state') != "APPROVED" ]]; do
                echo "Still waiting for approval..."
                sleep 10
              done
              echo "Code review approved!"
            else
              echo "Unit tests failed. Terminating the workflow."
              exit 1
            fi
